name: Todoist Test Automation using Python

on:
  [push]
  
jobs:
  api-testing:
    runs-on: ubuntu-latest
    env:
      USERNAME_ENV: ${{ secrets.TODOIST_USERNAME }}
      PASSWORD_ENV: ${{ secrets.TODOIST_PASSWORD }}
      TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.8'
    - name: Install Dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run API tests
      run: poetry run behave features/api
