name: Todoist Test Automation using Python

on:
  [push, pull_request]
  
jobs:
  api-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run API tests
      env:
        TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
      run: poetry run behave features/api

  ui-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - {os: "Windows", osVersion: "10", browserName: "Chrome", browserVersion: "latest"}
          - {os: "OS X", osVersion: "Monterey", browserName: "Chrome", browserVersion: "latest"}
    steps:
    - name: BrowserStack Env Setup
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: BrowserStack Local Tunnel Setup
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: random
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run API tests
      env:
        USERNAME_ENV: ${{ secrets.TODOIST_USERNAME }}
        PASSWORD_ENV: ${{ secrets.TODOIST_PASSWORD }}
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        RUN_ON_BROWSERSTACK: True
      run: poetry run behave features/ui -D os="${{ matrix.platform.os }}" -D os_version="${{ matrix.platform.osVersion }}" -D browser="${{ matrix.platform.browserName }}" -D browser_version="${{ matrix.platform.browserVersion }}"

    - name: BrowserStackLocal Stop
      uses: browserstack/github-actions/setup-local@master
      with:
          local-testing: stop