name: Todoist Test Automation using Python

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME_ENV: ${{ secrets.TODOIST_USERNAME }}
      PASSWORD_ENV: ${{ secrets.TODOIST_PASSWORD }}
      TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.8'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Install Tree Utility
      run: sudo apt-get install tree
    - name: Print Directory Tree
      run: tree -a
    - name: Run API tests
      run: |
        poetry run behave ./features/api
